# Generated by Django 4.1.1 on 2022-10-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_location_user_location_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location_id',
            new_name='location',
        ),
    ]
