# Generated by Django 4.1.1 on 2022-10-04 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_location_user_locations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
