# Generated by Django 4.1.1 on 2022-10-05 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_location_user_location_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location_id',
            new_name='location',
        ),
    ]
